-- 코드를 입력하세요
SELECT P.PRODUCT_CODE, sum(P.PRICE * S.SALES_AMOUNT) as SALES
FROM PRODUCT P
JOIN OFFLINE_SALE S on P.PRODUCT_ID =S.PRODUCT_ID
group by P.PRODUCT_CODE
order by SALES desc , P.PRODUCT_CODE
