-- 코드를 입력하세요
SELECT I.REST_ID, I.REST_NAME,I.FOOD_TYPE,I.FAVORITES,I.ADDRESS,round(avg(R.REVIEW_SCORE),2) as SCORE
FROM REST_INFO I JOIN REST_REVIEW R on I.REST_ID = R.REST_ID
WHERE I.ADDRESS like '서울%'
GROUP BY I.REST_ID
order by SCORE desc,I.FAVORITES desc