-- 코드를 작성해주세요
SELECT 
    case
        WHEN MONTH(DIFFERENTIATION_DATE) <=3 then '1Q'
        WHEN MONTH(DIFFERENTIATION_DATE) <=6 then '2Q'
        WHEN MONTH(DIFFERENTIATION_DATE) <=9 then '3Q'
        ELSE '4Q'
    END as QUARTER,
    COUNT(*) as ECOLI_COUNT
FROM ECOLI_DATA
GROUP BY QUARTER
ORDER BY QUARTER;