-- 코드를 입력하세요
SELECT U.USER_ID,U.NICKNAME,sum(B.PRICE) as TOTAL_SALES
FROM USED_GOODS_BOARD B
JOIN USED_GOODS_USER U on B.WRITER_ID = U.USER_ID
WHERE B.STATUS like 'DONE'
group by B.WRITER_ID
having TOTAL_SALES >=700000
order by TOTAL_SALES