-- 코드를 작성해주세요
SELECT count(*) as FISH_COUNT
FROM FISH_INFO 
WHERE
    FISH_TYPE = (SELECT FISH_TYPE FROM FISH_NAME_INFO WHERE FISH_NAME = 'BASS')
    OR
    FISH_TYPE = (SELECT FISH_TYPE FROM FISH_NAME_INFO WHERE FISH_NAME = 'SNAPPER')
