-- 코드를 입력하세요
SELECT H.CAR_ID
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H
JOIN (SELECT CAR_ID FROM CAR_RENTAL_COMPANY_CAR 
      WHERE CAR_TYPE = '세단') C on H.CAR_ID = C.CAR_ID
WHERE MONTH(START_DATE) = 10
group by H.CAR_ID
order by H.CAR_ID desc