-- 코드를 작성해주세요
SELECT G.SCORE, E.EMP_NO,E.EMP_NAME,E.POSITION,E.EMAIL
FROM HR_EMPLOYEES E
JOIN (SELECT EMP_NO, sum(SCORE) as SCORE
     FROM HR_GRADE 
     WHERE YEAR = 2022
     group by EMP_NO
     ) G on E.EMP_NO = G.EMP_NO
order by G.SCORE desc
limit 1;