-- 코드를 입력하세요
SELECT B.TITLE,B.BOARD_ID,R.REPLY_ID,R.WRITER_ID,R.CONTENTS,R.CREATED_DATE
FROM USED_GOODS_BOARD B JOIN USED_GOODS_REPLY R on B.BOARD_ID = R.BOARD_ID
WHERE YEAR(B.CREATED_DATE) = 2022 and MONTH(B.CREATED_DATE) = 10
order by R.CREATED_DATE , B.TITLE