-- 코드를 입력하세요
SELECT B.CATEGORY,sum(S.SALES) as TOTAL_SALES
FROM BOOK B
JOIN BOOK_SALES S on B.BOOK_ID = S.BOOK_ID
WHERE YEAR(S.SALES_DATE) = 2022 and MONTH(S.SALES_DATE) = 1
GROUP BY B.CATEGORY
order by B.CATEGORY